// @ts-nocheck
import Head from "next/head";
import Image from "next/image";
import About from "../Components/About";
import Contact from "../Components/Contact";
import Main from "../Components/Main";
import Navbar from "../Components/navbar";
import Projects from "../Components/Projects";
import Skills from "../Components/Skills";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </div>
  );
}
